Create the skeleton structure for the app
jbasden/ServerlessAppRepoMetricPublisher pull request #2
Opened 2018-06-08 22:30 UTC by jbasden

This commit creates the metric_publisher directory and the associated files.
app.py shows up as green because I added it back in. Other than that, there has been no code added. I just created the folders and files needed.

2018-06-08 22:43 UTC, jlhood requested changes
You have *.pyc files in your changes. Those should never be checked into source. You probably forgot to copy the hidden .gitignore file generated by sam init when you copied files out of sam-app. You have to explicitly copy that file out since it's a linux hidden file (starts with .). That will prevent git from trying to add those files to the index.

Also, python convention is to try to minimize underscores in module names so call this directory metricpublisher.

2018-06-08 22:49 UTC, ylynn requested changes
Change directory name metric_publisher to metricpublisher. Also add skeleton unit test files.

2018-06-08 23:23 UTC, jlhood reviewed
+1 to Wujing's comment to add skeleton unit test as well.

2018-06-09 00:12 UTC, jlhood approved these changes

2018-06-09 05:54 UTC, ylynn approved these changes

2018-06-09 05:54 UTC, ylynn approved these changes

2018-06-11 17:39 UTC, merged